### ISSUE TITLE
Atualizar a tabela

### ISSUE THREAD

**Issue by Diogo746** [RonierisonMaciel/senac#1]
https://github.com/RonierisonMaciel/senac/blob/cb3f4123864e8370d26cc2d474e8bbe32c2f5102/DB/DB-1/script/aulas_db-1.sql#L9

Atualizar a tabela com as informações novas da aula de hoje (17/09)

**Comment by 0x03c1** [comment]
@Diogo746, você lembra quais era os atributos?

**Comment by Diogo746** [comment]
> @Diogo746, você lembra quais era os atributos?

CREATE TABLE departamentos(
id  INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(100),
bloco VARCHAR(50),
data_criacao DATE  
);
